apiVersion: v1
kind: ConfigMap
metadata:
  name: fintech-common-config
  namespace: fintech-platform
data:
  KAFKA_BOOTSTRAP_SERVERS: "fintech-kafka:9092"
  POSTGRES_HOST: "fintech-postgres"
  POSTGRES_PORT: "5432"
  ACCOUNT_SERVICE_URL: "http://account-service.fintech-platform.svc.cluster.local:8081"
---
apiVersion: v1
kind: Secret
metadata:
  name: fintech-db-secret
  namespace: fintech-platform
type: Opaque
stringData:
  POSTGRES_USERNAME: "postgres"
  POSTGRES_PASSWORD: "postgrespassword"